version: '3'

services:
    web:
      build: 
        context: ./web_frontv2
        args:
          - VUE_APP_BACKEND=http://192.168.178.29:8080
      container_name: adwebinterface
      ports:
        - "80:8080"
    datasafe:
      environment:
        - SYNCER_REMOTE_URL=http://192.168.178.29:36144
        - CRACKER_REMOTE_URL=http://192.168.178.29:36145
      build: 
        context: ./data_safe
          
      container_name: addatasafe
      ports:
        - "8080:8080"
    syncer:
      build: ./syncer
      container_name: adsyncer
      ports:
        - "36144:8080"
    cracker:
      build: ./cracker
      container_name: adcracker
      ports:
        - "36145:8080"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
        