version: '3'

services:
    web:

         
      build: 
        context: ./web_front
        args:
          - VUE_APP_SYNCER_REMOTE_URL=http://127.0.0.1:36144
          - VUE_APP_CRACKER_REMOTE_URL=http://127.0.0.1:36145
      container_name: adwebinterface
      ports:
        - "80:8080"
    syncer:
      build: ./syncer
      container_name: adsyncer
      ports:
        - "36144:8080"
    cracker:
      build: ./cracker
      container_name: adcracker
      ports:
        - "36145:8080"
      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
        