version: '3'

services:
    web:
      build: 
        context: ./web_frontv2
        args:
          - VUE_APP_BACKEND=http://192.168.178.29:8080
      container_name: adwebinterface
      ports:
        - "80:8080"
    datasafe:
      build: 
        context: ./data_safe
      networks:
        - adnet
      container_name: addatasafe
      ports:
        - "8080:8080"

    syncer:
      build: ./syncer
      networks:
        - adnet
      container_name: adsyncer


    cracker:
      build: ./cracker
      networks:
        - adnet
      container_name: adcracker

      deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
networks:
  adnet:
    driver: bridge
